### ISSUE TITLE
Initial returned count for :count_hit is always 1

### ISSUE THREAD

**Issue by davelively14** [ExHammer/hammer-backend-redis#17]
When sending `{:count_hit, key, now, increment}` to this backend, the count result will always be 1, regardless of the value passed to `increment`.

The issue is on [line 261](https://github.com/ExHammer/hammer-backend-redis/blob/master/lib/hammer_backend_redis.ex#L261), where upon successful creation of the entry in Redis, we return `{:ok, 1}`. That should be `{:ok, increment}`. 

I submitted a PR here: https://github.com/ExHammer/hammer-backend-redis/pull/16

**Comment by ShaneKilkelly** [comment]
Fixed in version 6.1
