### ISSUE TITLE
Resetting Hammer.Backend.Redis in tests

### ISSUE THREAD

**Issue by mathiasose** [ExHammer/hammer-backend-redis#19]
Essentially the same question as https://github.com/ExHammer/hammer/issues/35, but for this backend.

This lib is running smoothly in production, but when I try to write tests to assert the behavior of the rate limiting, things get flaky depending on the run order of the tests.

Is there an appropriate function that I can use in my tests to reset all counters? I see there is `delete_buckets(pid, id)`, but that takes arguments I'm not sure about.

**Comment by epinault** [comment]
is this still needed?
