### ISSUE TITLE
stale repo?

### ISSUE THREAD

**Issue by epinault** [ExHammer/hammer-backend-redis#25]
Is this actively maintained? do you need more maintainers?

**Comment by rafaelsiqueira** [comment]
I'd love help too. I'm using it in production here.

**Comment by epinault** [comment]
@Gazler @sobolevn @slashdotdash @rosswilson  There are people who are willing to help and contribute if you are too busy and need new maintainers. But can any of you help us ? I have a fork with all we need but I would much prefer to keep this alive

**Comment by JuneKelly** [comment]
Related answer in https://github.com/ExHammer/hammer/issues/48 . TLDR: I'm happy to hand over this project to a group of new maintainers.

**Comment by epinault** [comment]
Yes ! Would love too as my company depends on it and I would like to merge a fork I maintain with many MR from here and updates

**Comment by epinault** [comment]
took over and pushed an update today. sorry took so long! trying to make it better moving forward
