### ISSUE TITLE
Please publish a release (6.1.1?) to hex.pm

### ISSUE THREAD

**Issue by soundmonster** [ExHammer/hammer-backend-redis#29]
This would be greatly appreciated! 🙏 ❤️

**Comment by amalbuquerque** [comment]
@epinault first of all super thank you for picking `:hammer` and its other libraries as a maintainer 🙏 

Do you think we could release a new version? There are some PRs open, but even the improvement with https://github.com/ExHammer/hammer-backend-redis/commit/c43a7ea269e70f10621694e74ae977f4b71bf826 could warrant a new 6.1.1 release, WDYT?

Thank you again!

**Comment by epinault** [comment]
yes! sorry about the delay. Working with my company to get this all in shape. I ll spend some time on Friday this week, would that work?

**Comment by amalbuquerque** [comment]
That's awesome, thank you @epinault 🙏

**Comment by epinault** [comment]
done!
