### ISSUE TITLE
6.1.1 does not include latest changes

### ISSUE THREAD

**Issue by martosaur** [ExHammer/hammer-backend-redis#35]
If you [preview](https://preview.hex.pm/preview/hammer_backend_redis/6.1.1/show/mix.exs) 6.1.1 code on Hex it does not include latest changes, primarily https://github.com/ExHammer/hammer-backend-redis/pull/28

Not sure which revision it was assembled from

**Comment by epinault** [comment]
yea I think I unfortunately shipped from a fork (which has the same changes). I am working on more stuff and should be able to release a new version tomorrow if thats ok to wait till then?

**Comment by epinault** [comment]
just release 6.1.2
